import express from "express";
import { adminPostAdd, adminVidPostAdd, approveNewsVid,approveNews, loginAdmin, addReporter} from "./Controllers/Admin.js";
import { loginReporter } from "./Controllers/Reporter.js";
import { getNewsData, UserLogin, UserSignup } from "./Controllers/User.js";
import {addComment,likeNews} from "./Controllers/Comments.js";
import { deleteNews, updateNews } from "./Controllers/EditNews.js";
const router = express.Router();
router.post("/loginAdmin", loginAdmin);
router.post("/loginReporter", loginReporter);
router.post("/adminPostAdd",adminPostAdd);
router.post("/adminVidPostAdd",adminVidPostAdd);
router.post("/approveNews",approveNews);
router.post("/approveNewsVid",approveNewsVid);
router.post("/getNewsData",getNewsData);
router.post("/UserLogin", UserLogin);
router.post("/UserSignup", UserSignup);
router.post("/newsUpdate", updateNews);
router.post("/deleteNews", deleteNews);
router.post("/addReporter", addReporter);

export default router;
